name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  coding-standard:
    name: Coding Standard (PSR-12)
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Git Files Changed
        id: changes
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/develop:refs/remotes/origin/develop
          echo changedFiles=$(git diff --diff-filter=ACMRT --name-only origin/develop HEAD | xargs) >> $GITHUB_OUTPUT
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.2
          ini-values: memory_limit=-1
          extensions: imagick, bcmath, mysqli, intl, pdo_mysql, opcache, gd, xsl, zip, soap, pcntl, sockets
        env:
          APP_ENV: prod
      - name: Composer install
        uses: ramsey/composer-install@v2
        with:
          composer-options: --profile --ignore-platform-reqs
      - name: PHP Mess Detector
        run: | 
            php bin/phpmd src/ test/ text phpmd.xml
      - name: PHP Code Sniffer
        run: |
             php bin/phpcs --standard=PSR12 src/ tests/
      - name: PHPStan Static Analysis
        run: |
             php bin/phpstan analyse src/ tests/